name: CCIP
channels:
    - conda-forge
    - bioconda
    - https://repo.anaconda.com/pkgs/main
    - https://repo.anaconda.com/pkgs/r
dependencies:
    - snakemake==8.28.0
    - python==3.12.9
    - pip==25.0.1